// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyfdccbnjahyaokmhphk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5ZmRjY2JuamFoeWFva21ocGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTM1ODUsImV4cCI6MjA3MDA2OTU4NX0.HyGALnr8zZTaPcwggLGUnKCll7tlID_ogPUyNwDTxdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});